title: Alma F. Chan Chin # your name (or website title) here
logo: "/images/55518358_1176383372534268_4490149572210851840_o.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Higher University Technician in Information Technologies Multimedia Area and Electronic Commerce.
  <br><br>
  Email: almachanchin@gmail.com 
  <br>
  cell phone: 99-11-16-57-97
  <br><br>
    
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
